# Generated by Django 5.0.2 on 2024-03-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
                ('objetivo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('funcoes', models.TextField()),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
                ('presente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FormacaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('termino', models.DateField(blank=True, null=True)),
                ('presente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
            ],
        ),
    ]
