# Generated by Django 5.0.2 on 2024-03-30 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='curriculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.curriculo'),
        ),
        migrations.AddField(
            model_name='formacaoacademica',
            name='curriculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.curriculo'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='curriculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.curriculo'),
        ),
    ]
