# Generated by Django 5.0.2 on 2024-03-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculo',
            name='funcao',
        ),
    ]
