# Generated by Django 5.0.2 on 2024-03-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_funcao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencia',
            name='funcoes',
        ),
    ]
