# Generated by Django 5.0.2 on 2024-03-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_remove_experiencia_funcoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
