# Generated by Django 5.0.2 on 2024-03-30 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_experiencia_termino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='inicio',
            new_name='periodo',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='termino',
        ),
    ]
