# Generated by Django 5.0.2 on 2024-03-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_rename_inicio_projeto_periodo_remove_projeto_termino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(),
        ),
    ]
